// Module switcher catalogue — every merged module workspace, grouped.
// Auth/login/registration screens are intentionally excluded.

export type ModuleGroup = { group: string; items: { label: string; path: string }[] };

export const MODULE_GROUPS: ModuleGroup[] = [
  {
    group: "Control & Admin",
    items: [
      { label: "Control Panel", path: "/dashboard" },
      { label: "Boss Panel", path: "/boss/dashboard" },
      { label: "Boss Fortress", path: "/boss-fortress" },
      { label: "CEO Dashboard", path: "/ceo/dashboard" },
      { label: "AI CEO", path: "/ai-ceo" },
      { label: "Super Admin", path: "/super-admin" },
      { label: "Super Admin System", path: "/super-admin-system/dashboard" },
      { label: "Role Center", path: "/super-admin-system/role-center" },
      { label: "Role Switch", path: "/super-admin-system/role-switch" },
      { label: "Permission Matrix", path: "/super-admin/permission-matrix" },
      { label: "Master Admin", path: "/master-admin" },
      { label: "Master Admin Supreme", path: "/master-admin-supreme" },
      { label: "Owner Panel", path: "/owner" },
      { label: "Admin Dashboard", path: "/admin/dashboard" },
      { label: "Role Manager", path: "/admin/role-manager" },
      { label: "Bulk Users", path: "/admin/bulk-users" },
      { label: "Enterprise Control", path: "/enterprise-control" },
      { label: "Unified Command Center", path: "/super-admin/command-center" },
    ],
  },
  {
    group: "AI & Developer",
    items: [
      { label: "Vala AI Console", path: "/ai-console" },
      { label: "AI API Manager", path: "/api-manager" },
      { label: "API Integrations", path: "/api-integrations" },
      { label: "AI Billing", path: "/super-admin/ai-billing" },
      { label: "Auto Dev Engine", path: "/auto-dev" },
      { label: "Dev Manager", path: "/dev-manager" },
      { label: "Dev Command Center", path: "/dev-command-center" },
      { label: "Developer Dashboard", path: "/developer-dashboard" },
      { label: "Server Manager", path: "/server-manager" },
      { label: "Server Portal", path: "/server-portal" },
      { label: "R&D Dashboard", path: "/rnd-dashboard" },
      { label: "Performance", path: "/performance" },
      { label: "Incident & Crisis", path: "/incident-crisis" },
    ],
  },
  {
    group: "Business Operations",
    items: [
      { label: "Sales", path: "/sales" },
      { label: "Sales CRM", path: "/sales-crm" },
      { label: "Sales & Support", path: "/sales-support" },
      { label: "Sales Support Manager", path: "/sales-support-manager" },
      { label: "Customer Support", path: "/client-success" },
      { label: "Lead Manager", path: "/lead-manager" },
      { label: "Marketing", path: "/marketing" },
      { label: "Marketing Manager", path: "/marketing-manager" },
      { label: "Enterprise Marketing", path: "/enterprise/marketing" },
      { label: "SEO Manager", path: "/seo-manager" },
      { label: "SEO Dashboard", path: "/seo-dashboard" },
      { label: "Assist Manager", path: "/assist-manager" },
      { label: "Safe Assist", path: "/safe-assist" },
      { label: "Task Manager", path: "/promise-management" },
      { label: "Promise Tracker", path: "/promise-tracker" },
      { label: "Internal Chat", path: "/internal-chat" },
      { label: "HR Manager", path: "/hr-manager" },
      { label: "HR Dashboard", path: "/hr-dashboard" },
      { label: "Finance Manager", path: "/finance" },
      { label: "Finance Center", path: "/super-admin/finance-center" },
      { label: "Legal Manager", path: "/legal-manager" },
      { label: "Compliance Center", path: "/super-admin/compliance-center" },
      { label: "Security Command", path: "/security-command" },
      { label: "Retail POS", path: "/retail-pos" },
      { label: "Settings", path: "/settings" },
    ],
  },
  {
    group: "Partners & Network",
    items: [
      { label: "Franchise Owner", path: "/franchise/dashboard" },
      { label: "Franchise Manager", path: "/super-admin/franchise-manager" },
      { label: "Franchise CRM", path: "/franchise/crm" },
      { label: "Franchise Sales Center", path: "/franchise/sales-center" },
      { label: "Franchise Wallet", path: "/franchise/wallet" },
      { label: "Reseller Dashboard", path: "/reseller-dashboard" },
      { label: "Reseller Manager", path: "/reseller-manager" },
      { label: "Reseller Portal", path: "/reseller/portal" },
      { label: "Influencer Dashboard", path: "/influencer-dashboard" },
      { label: "Influencer Manager", path: "/influencer-manager" },
      { label: "Influencer Command Center", path: "/influencer/command-center" },
      { label: "Prime User", path: "/prime/dashboard" },
      { label: "Pro Manager", path: "/product-demo-manager" },
      { label: "Client Portal", path: "/client-portal" },
      { label: "Continent Admin", path: "/continent/dashboard" },
      { label: "Country Admin", path: "/country/dashboard" },
      { label: "Area Manager", path: "/area-manager" },
    ],
  },
  {
    group: "Products & Demos",
    items: [
      { label: "Product Manager", path: "/super-admin/product-manager" },
      { label: "Products", path: "/products" },
      { label: "Demo Manager", path: "/demo-manager" },
      { label: "Demo Directory", path: "/demo-directory" },
      { label: "All Demos", path: "/demos" },
      { label: "Premium Demos", path: "/premium-demos" },
      { label: "School ERP", path: "/school-software/dashboard" },
      { label: "Sectors", path: "/sectors" },
      { label: "Showcase", path: "/showcase" },
      { label: "Pricing", path: "/pricing" },
    ],
  },
  {
    group: "Recognition (AMS)",
    items: [
      { label: "Command Center", path: "/command-center" },
      { label: "AMS Manager", path: "/ams" },
      { label: "Achievements", path: "/achievements" },
      { label: "Awards", path: "/awards" },
      { label: "Badges", path: "/badges" },
      { label: "Trophies", path: "/trophies" },
      { label: "Trophy Gallery", path: "/trophy-gallery" },
      { label: "Certificates", path: "/certificates" },
      { label: "Ranks", path: "/ranks" },
      { label: "Levels", path: "/levels" },
      { label: "XP", path: "/xp" },
      { label: "Missions", path: "/missions" },
      { label: "Quests", path: "/quests" },
      { label: "Challenges", path: "/challenges" },
      { label: "Rewards", path: "/rewards" },
      { label: "Collections", path: "/collections" },
      { label: "Leaderboards", path: "/leaderboards" },
      { label: "Hall of Fame", path: "/hall-of-fame" },
      { label: "Legacy", path: "/legacy" },
      { label: "Passport", path: "/passport" },
      { label: "Identity", path: "/identity" },
      { label: "Reputation Vault", path: "/reputation-vault" },
      { label: "Role Manager (AMS)", path: "/role-manager" },
      { label: "Analytics", path: "/analytics" },
      { label: "Audit", path: "/audit" },
      { label: "Claims", path: "/claims" },
      { label: "Chat", path: "/chat" },
      { label: "Notifications", path: "/notifications" },
      { label: "AMS Settings", path: "/settings" },
    ],
  },
  {
    group: "Vaults",
    items: [
      { label: "Achievement Vault", path: "/achievement-vault" },
      { label: "Award Vault", path: "/award-vault" },
      { label: "Badge Vault", path: "/badge-vault" },
      { label: "Trophy Vault", path: "/trophy-vault" },
      { label: "Certificate Vault", path: "/certificate-vault" },
      { label: "Passport Vault", path: "/passport-vault" },
      { label: "Rank Vault", path: "/rank-vault" },
      { label: "Membership Vault", path: "/membership-vault" },
      { label: "Identity Card Vault", path: "/identity-card-vault" },
      { label: "License Card Vault", path: "/license-card-vault" },
      { label: "Honor Coin Vault", path: "/honor-coin-vault" },
      { label: "Recognition Coin Vault", path: "/recognition-coin-vault" },
      { label: "XP Crystal Vault", path: "/xp-crystal-vault" },
      { label: "Reward Chest Vault", path: "/reward-chest-vault" },
      { label: "Legacy Medal Vault", path: "/legacy-medal-vault" },
      { label: "Founder Seal Vault", path: "/founder-seal-vault" },
      { label: "Trust Seal Vault", path: "/trust-seal-vault" },
      { label: "Verification Vault", path: "/verification-vault" },
      { label: "Hall of Fame Vault", path: "/hall-of-fame-vault" },
    ],
  },
  {
    group: "Progression",
    items: [
      { label: "Author Progression", path: "/author-progression" },
      { label: "Vendor Progression", path: "/vendor-progression" },
      { label: "Developer Progression", path: "/developer-progression" },
      { label: "Role Showcase", path: "/role-showcase" },
      { label: "AI Studio", path: "/ai" },
    ],
  },
];