// @ts-nocheck
import type { SoundTone } from '@/hooks/useNotificationSound';

export interface NotificationTemplate {
  title: string;
  message: string;
  tone: SoundTone;
  icon: string;
  accentColor: string;
}

export type NotificationCategory = 
  | 'new_task'
  | 'lead_opportunity'
  | 'demo_request'
  | 'client_feedback'
  | 'transaction'
  | 'campaign_update'
  | 'compliance'
  | 'talent'
  | 'priority_request'
  | 'system_insight'
  | 'performance_insight'
  | 'growth_opportunity'
  | 'engagement'
  | 'workflow'
  | 'innovation';

export const roleTemplates: Record<string, Record<NotificationCategory, NotificationTemplate>> = {
  super_admin: {
    system_insight: {
      title: 'System Insight',
      message: 'A new update requires your leadership attention. Review and guide the best path ahead.',
      tone: 'vip_bell',
      icon: 'Crown',
      accentColor: 'from-amber-500 to-yellow-500',
    },
    new_task: {
      title: 'Leadership Review',
      message: 'A strategic decision awaits your direction. Your guidance shapes success.',
      tone: 'vip_bell',
      icon: 'Shield',
      accentColor: 'from-purple-500 to-indigo-500',
    },
    lead_opportunity: { title: 'Global Lead Alert', message: 'A high-value opportunity has emerged. Strategic alignment recommended.', tone: 'golden_vip_bell', icon: 'Globe', accentColor: 'from-emerald-500 to-teal-500' },
    demo_request: { title: 'Demo Oversight', message: 'Demo activity requires executive attention.', tone: 'soft_bell', icon: 'Monitor', accentColor: 'from-blue-500 to-cyan-500' },
    client_feedback: { title: 'VIP Feedback', message: 'Premium client input received. Your touch elevates experience.', tone: 'golden_vip_bell', icon: 'Star', accentColor: 'from-amber-500 to-orange-500' },
    transaction: { title: 'Financial Insight', message: 'Significant transaction requires oversight.', tone: 'soft_bass_bell', icon: 'DollarSign', accentColor: 'from-green-500 to-emerald-500' },
    campaign_update: { title: 'Campaign Performance', message: 'Marketing metrics show notable patterns.', tone: 'success_chime', icon: 'TrendingUp', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Compliance Status', message: 'Regulatory alignment needs verification.', tone: 'low_ping', icon: 'FileCheck', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Talent Pipeline', message: 'Hiring decisions await your direction.', tone: 'soft_bell', icon: 'Users', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Priority Escalation', message: 'Urgent matter requires immediate attention.', tone: 'critical_buzzer', icon: 'AlertTriangle', accentColor: 'from-red-500 to-rose-500' },
    performance_insight: { title: 'Performance Overview', message: 'Team metrics reveal optimization opportunities.', tone: 'info_bell', icon: 'BarChart', accentColor: 'from-cyan-500 to-blue-500' },
    growth_opportunity: { title: 'Growth Signal', message: 'Market indicators suggest expansion path.', tone: 'vip_bell', icon: 'Rocket', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Engagement Metrics', message: 'Platform activity shows positive trends.', tone: 'success_chime', icon: 'Activity', accentColor: 'from-green-500 to-teal-500' },
    workflow: { title: 'Workflow Status', message: 'Operational flow requires oversight.', tone: 'low_ping', icon: 'GitBranch', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'Innovation Alert', message: 'R&D breakthrough warrants review.', tone: 'golden_vip_bell', icon: 'Lightbulb', accentColor: 'from-yellow-500 to-amber-500' },
  },
  franchise: {
    lead_opportunity: {
      title: 'Lead Opportunity',
      message: 'A potential client in your region is awaiting support. Your guidance can turn this into success.',
      tone: 'soft_bell',
      icon: 'UserPlus',
      accentColor: 'from-emerald-500 to-green-500',
    },
    new_task: { title: 'Territory Update', message: 'New activity in your region requires attention.', tone: 'soft_bell', icon: 'MapPin', accentColor: 'from-blue-500 to-indigo-500' },
    demo_request: { title: 'Demo Interest', message: 'A prospect is eager to see what you offer. Share your expertise.', tone: 'success_chime', icon: 'Presentation', accentColor: 'from-purple-500 to-violet-500' },
    client_feedback: { title: 'Client Voice', message: 'Feedback received. Your response strengthens relationships.', tone: 'soft_bell', icon: 'MessageCircle', accentColor: 'from-cyan-500 to-teal-500' },
    transaction: { title: 'Commission Update', message: 'Your earnings reflect your dedication.', tone: 'success_chime', icon: 'Wallet', accentColor: 'from-green-500 to-emerald-500' },
    campaign_update: { title: 'Local Campaign', message: 'Your marketing efforts are gaining traction.', tone: 'success_chime', icon: 'Megaphone', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Compliance Check', message: 'Territory documentation needs your review.', tone: 'low_ping', icon: 'ClipboardCheck', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Team Growth', message: 'Reseller application in your territory.', tone: 'info_bell', icon: 'UserCheck', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Priority Lead', message: 'High-value prospect needs immediate engagement.', tone: 'vip_bell', icon: 'Zap', accentColor: 'from-amber-500 to-orange-500' },
    system_insight: { title: 'Territory Insight', message: 'Performance data reveals growth paths.', tone: 'info_bell', icon: 'PieChart', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Performance Review', message: 'Your metrics show progress. Keep building momentum.', tone: 'success_chime', icon: 'TrendingUp', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'Expansion Opportunity', message: 'New territory potential identified.', tone: 'vip_bell', icon: 'Map', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Client Engagement', message: 'Your efforts are creating positive impact.', tone: 'success_chime', icon: 'Heart', accentColor: 'from-rose-500 to-pink-500' },
    workflow: { title: 'Pipeline Flow', message: 'Lead pipeline needs your attention.', tone: 'low_ping', icon: 'Filter', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'New Feature', message: 'New tools available to enhance your reach.', tone: 'info_bell', icon: 'Sparkles', accentColor: 'from-yellow-500 to-amber-500' },
  },
  reseller: {
    demo_request: {
      title: 'Sales Momentum',
      message: 'A fresh demo request is live. Share confidently—your next conversion could be here.',
      tone: 'success_chime',
      icon: 'Play',
      accentColor: 'from-green-500 to-emerald-500',
    },
    lead_opportunity: { title: 'New Prospect', message: 'An interested client awaits your expertise.', tone: 'soft_bell', icon: 'UserPlus', accentColor: 'from-blue-500 to-cyan-500' },
    new_task: { title: 'Action Item', message: 'A new opportunity is ready for your follow-up.', tone: 'soft_bell', icon: 'CheckCircle', accentColor: 'from-purple-500 to-indigo-500' },
    client_feedback: { title: 'Client Response', message: 'Feedback received—your dedication makes a difference.', tone: 'soft_bell', icon: 'ThumbsUp', accentColor: 'from-cyan-500 to-teal-500' },
    transaction: { title: 'Earnings Update', message: 'Your wallet reflects your hard work.', tone: 'success_chime', icon: 'DollarSign', accentColor: 'from-green-500 to-emerald-500' },
    campaign_update: { title: 'Promo Update', message: 'Your promotional content is gaining views.', tone: 'success_chime', icon: 'Eye', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Documentation', message: 'Please review your account documents.', tone: 'low_ping', icon: 'FileText', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Team Invite', message: 'Opportunity to expand your network.', tone: 'info_bell', icon: 'Users', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Hot Lead', message: 'A high-intent prospect needs quick response.', tone: 'vip_bell', icon: 'Flame', accentColor: 'from-orange-500 to-red-500' },
    system_insight: { title: 'Sales Insight', message: 'Your conversion data shows patterns.', tone: 'info_bell', icon: 'BarChart2', accentColor: 'from-blue-500 to-indigo-500' },
    performance_insight: { title: 'Your Progress', message: 'Your sales trajectory is climbing.', tone: 'success_chime', icon: 'ArrowUp', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'Growth Path', message: 'New products available for your catalog.', tone: 'vip_bell', icon: 'Package', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Client Interest', message: 'Your demos are generating engagement.', tone: 'success_chime', icon: 'MousePointer', accentColor: 'from-cyan-500 to-blue-500' },
    workflow: { title: 'Follow-Up Due', message: 'Scheduled follow-ups await your attention.', tone: 'low_ping', icon: 'Clock', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'New Tools', message: 'Enhanced selling tools now available.', tone: 'info_bell', icon: 'Wrench', accentColor: 'from-yellow-500 to-amber-500' },
  },
  developer: {
    new_task: {
      title: 'New Task Ready',
      message: 'A project is ready for your expertise. Accept the promise when you are prepared to deliver.',
      tone: 'minimal_ping',
      icon: 'Code',
      accentColor: 'from-violet-500 to-purple-500',
    },
    lead_opportunity: { title: 'Client Request', message: 'A client has a technical need matching your skills.', tone: 'minimal_ping', icon: 'Briefcase', accentColor: 'from-blue-500 to-indigo-500' },
    demo_request: { title: 'Demo Enhancement', message: 'A demo needs your technical expertise.', tone: 'minimal_ping', icon: 'Monitor', accentColor: 'from-cyan-500 to-teal-500' },
    client_feedback: { title: 'Code Review', message: 'Client feedback on your delivery is available.', tone: 'soft_bell', icon: 'MessageSquare', accentColor: 'from-green-500 to-emerald-500' },
    transaction: { title: 'Payment Processed', message: 'Your earnings have been credited.', tone: 'success_chime', icon: 'CreditCard', accentColor: 'from-green-500 to-teal-500' },
    campaign_update: { title: 'Project Update', message: 'Project milestone approaching.', tone: 'pending_tick', icon: 'Flag', accentColor: 'from-amber-500 to-orange-500' },
    compliance: { title: 'NDA Reminder', message: 'Documentation requires your acknowledgment.', tone: 'low_ping', icon: 'Shield', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Skill Match', message: 'New project matches your expertise.', tone: 'minimal_ping', icon: 'Award', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Priority Task', message: 'An urgent task requires your attention.', tone: 'warning_ping', icon: 'AlertCircle', accentColor: 'from-orange-500 to-red-500' },
    system_insight: { title: 'Performance Tip', message: 'Optimization opportunity identified.', tone: 'info_bell', icon: 'Cpu', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Quality Score', message: 'Your code quality metrics have updated.', tone: 'success_chime', icon: 'Star', accentColor: 'from-yellow-500 to-amber-500' },
    growth_opportunity: { title: 'Skill Growth', message: 'New technology training available.', tone: 'info_bell', icon: 'BookOpen', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Task Progress', message: 'Timer checkpoint approaching.', tone: 'pending_tick', icon: 'Clock', accentColor: 'from-cyan-500 to-blue-500' },
    workflow: { title: 'Workflow Update', message: 'Task pipeline has new items.', tone: 'minimal_ping', icon: 'GitPullRequest', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'Tech Update', message: 'New development tools available.', tone: 'info_bell', icon: 'Terminal', accentColor: 'from-green-500 to-teal-500' },
  },
  support: {
    client_feedback: {
      title: 'Client Experience',
      message: 'A customer seeks clarification. Respond to maintain our premium satisfaction standard.',
      tone: 'soft_bell',
      icon: 'Headphones',
      accentColor: 'from-blue-500 to-indigo-500',
    },
    new_task: { title: 'Support Request', message: 'A client needs your helpful guidance.', tone: 'soft_bell', icon: 'HelpCircle', accentColor: 'from-purple-500 to-violet-500' },
    lead_opportunity: { title: 'Upsell Opportunity', message: 'Client interest suggests upgrade potential.', tone: 'info_bell', icon: 'TrendingUp', accentColor: 'from-green-500 to-emerald-500' },
    demo_request: { title: 'Demo Support', message: 'Demo walkthrough assistance requested.', tone: 'soft_bell', icon: 'Play', accentColor: 'from-cyan-500 to-teal-500' },
    transaction: { title: 'Billing Query', message: 'Client has billing clarification needs.', tone: 'soft_bell', icon: 'Receipt', accentColor: 'from-amber-500 to-orange-500' },
    campaign_update: { title: 'Knowledge Base', message: 'New FAQ articles available.', tone: 'info_bell', icon: 'BookOpen', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Policy Update', message: 'Support policy changes need review.', tone: 'low_ping', icon: 'FileText', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Team Update', message: 'New support team member onboarding.', tone: 'info_bell', icon: 'UserPlus', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'VIP Support', message: 'Priority client needs immediate attention.', tone: 'vip_bell', icon: 'Crown', accentColor: 'from-amber-500 to-yellow-500' },
    system_insight: { title: 'Ticket Insights', message: 'Support metrics show improvement areas.', tone: 'info_bell', icon: 'BarChart', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Resolution Rate', message: 'Your support metrics are improving.', tone: 'success_chime', icon: 'CheckCircle', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'Training Available', message: 'New support skills training ready.', tone: 'info_bell', icon: 'GraduationCap', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Client Satisfaction', message: 'Positive feedback received.', tone: 'success_chime', icon: 'Heart', accentColor: 'from-rose-500 to-pink-500' },
    workflow: { title: 'Queue Update', message: 'Ticket queue requires attention.', tone: 'low_ping', icon: 'Inbox', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'Tool Update', message: 'Enhanced support tools available.', tone: 'info_bell', icon: 'Wrench', accentColor: 'from-yellow-500 to-amber-500' },
  },
  prime: {
    priority_request: {
      title: 'Priority Touch',
      message: 'Your request has been received with highest priority. We are aligning resources now.',
      tone: 'golden_vip_bell',
      icon: 'Crown',
      accentColor: 'from-amber-400 to-yellow-500',
    },
    new_task: { title: 'Development Update', message: 'Your project has made progress.', tone: 'golden_vip_bell', icon: 'Sparkles', accentColor: 'from-purple-500 to-violet-500' },
    lead_opportunity: { title: 'VIP Offering', message: 'Exclusive feature available for you.', tone: 'golden_vip_bell', icon: 'Gift', accentColor: 'from-pink-500 to-rose-500' },
    demo_request: { title: 'Preview Access', message: 'Early access demo ready for you.', tone: 'vip_bell', icon: 'Eye', accentColor: 'from-blue-500 to-indigo-500' },
    client_feedback: { title: 'Your Voice Matters', message: 'Share your thoughts—we prioritize your input.', tone: 'golden_vip_bell', icon: 'MessageCircle', accentColor: 'from-cyan-500 to-teal-500' },
    transaction: { title: 'Account Update', message: 'Your subscription has been updated.', tone: 'success_chime', icon: 'CreditCard', accentColor: 'from-green-500 to-emerald-500' },
    campaign_update: { title: 'Exclusive Update', message: 'VIP-only content available.', tone: 'golden_vip_bell', icon: 'Star', accentColor: 'from-amber-500 to-orange-500' },
    compliance: { title: 'Account Review', message: 'Quick verification to ensure seamless service.', tone: 'soft_bell', icon: 'Shield', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Dedicated Support', message: 'Your personal team is ready.', tone: 'golden_vip_bell', icon: 'Users', accentColor: 'from-violet-500 to-purple-500' },
    system_insight: { title: 'Platform Update', message: 'New features designed with you in mind.', tone: 'vip_bell', icon: 'Zap', accentColor: 'from-yellow-500 to-amber-500' },
    performance_insight: { title: 'Usage Report', message: 'Your personalized analytics are ready.', tone: 'info_bell', icon: 'BarChart2', accentColor: 'from-blue-500 to-cyan-500' },
    growth_opportunity: { title: 'Upgrade Available', message: 'Enhanced features await your approval.', tone: 'golden_vip_bell', icon: 'ArrowUp', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Milestone Reached', message: 'Congratulations on your achievement.', tone: 'success_chime', icon: 'Trophy', accentColor: 'from-yellow-500 to-orange-500' },
    workflow: { title: 'Project Progress', message: 'Your timeline is on track.', tone: 'success_chime', icon: 'CheckCircle', accentColor: 'from-green-500 to-teal-500' },
    innovation: { title: 'First Look', message: 'Beta feature access granted.', tone: 'golden_vip_bell', icon: 'Lightbulb', accentColor: 'from-amber-400 to-yellow-500' },
  },
  finance: {
    transaction: {
      title: 'Transaction Review',
      message: 'Wallet movement requires confirmation. Validate for transparent accounting.',
      tone: 'soft_bass_bell',
      icon: 'DollarSign',
      accentColor: 'from-green-500 to-emerald-500',
    },
    new_task: { title: 'Finance Action', message: 'A financial item requires processing.', tone: 'soft_bell', icon: 'FileText', accentColor: 'from-blue-500 to-indigo-500' },
    lead_opportunity: { title: 'Revenue Signal', message: 'New revenue opportunity identified.', tone: 'info_bell', icon: 'TrendingUp', accentColor: 'from-cyan-500 to-teal-500' },
    demo_request: { title: 'Cost Analysis', message: 'Demo cost report ready for review.', tone: 'info_bell', icon: 'PieChart', accentColor: 'from-purple-500 to-violet-500' },
    client_feedback: { title: 'Payment Inquiry', message: 'Client billing question received.', tone: 'soft_bell', icon: 'HelpCircle', accentColor: 'from-amber-500 to-orange-500' },
    campaign_update: { title: 'Budget Update', message: 'Campaign spending summary available.', tone: 'info_bell', icon: 'Calculator', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Audit Preparation', message: 'Documentation ready for compliance review.', tone: 'low_ping', icon: 'ClipboardCheck', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Payroll Update', message: 'Payroll processing requires attention.', tone: 'soft_bell', icon: 'Users', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Urgent Transaction', message: 'High-priority financial matter needs review.', tone: 'warning_ping', icon: 'AlertTriangle', accentColor: 'from-red-500 to-rose-500' },
    system_insight: { title: 'Financial Insight', message: 'Cash flow patterns detected.', tone: 'info_bell', icon: 'BarChart', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Revenue Metrics', message: 'Performance data shows positive trends.', tone: 'success_chime', icon: 'ArrowUp', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'Investment Signal', message: 'Strategic opportunity identified.', tone: 'vip_bell', icon: 'Landmark', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Collection Update', message: 'Receivables status updated.', tone: 'info_bell', icon: 'Receipt', accentColor: 'from-cyan-500 to-blue-500' },
    workflow: { title: 'Approval Queue', message: 'Transactions await your approval.', tone: 'low_ping', icon: 'CheckSquare', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'Process Update', message: 'New financial tools available.', tone: 'info_bell', icon: 'Zap', accentColor: 'from-yellow-500 to-amber-500' },
  },
  marketing: {
    campaign_update: {
      title: 'Campaign Trigger',
      message: 'Your campaign analytics show a spike. Optimize to leverage momentum.',
      tone: 'success_chime',
      icon: 'Megaphone',
      accentColor: 'from-pink-500 to-rose-500',
    },
    new_task: { title: 'Creative Brief', message: 'New campaign awaits your creative touch.', tone: 'soft_bell', icon: 'Palette', accentColor: 'from-purple-500 to-violet-500' },
    lead_opportunity: { title: 'Audience Growth', message: 'New audience segment identified.', tone: 'info_bell', icon: 'Users', accentColor: 'from-blue-500 to-indigo-500' },
    demo_request: { title: 'Product Showcase', message: 'Demo content needs marketing polish.', tone: 'soft_bell', icon: 'Image', accentColor: 'from-cyan-500 to-teal-500' },
    client_feedback: { title: 'Market Response', message: 'Campaign feedback received.', tone: 'success_chime', icon: 'MessageCircle', accentColor: 'from-green-500 to-emerald-500' },
    transaction: { title: 'Ad Spend', message: 'Budget allocation needs review.', tone: 'info_bell', icon: 'CreditCard', accentColor: 'from-amber-500 to-orange-500' },
    compliance: { title: 'Brand Guidelines', message: 'Content compliance check needed.', tone: 'low_ping', icon: 'FileCheck', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Influencer Match', message: 'New collaboration opportunity.', tone: 'success_chime', icon: 'Star', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Viral Moment', message: 'Time-sensitive content opportunity.', tone: 'vip_bell', icon: 'Flame', accentColor: 'from-orange-500 to-red-500' },
    system_insight: { title: 'Analytics Insight', message: 'Campaign data reveals opportunities.', tone: 'info_bell', icon: 'BarChart2', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'ROI Update', message: 'Marketing metrics show strong returns.', tone: 'success_chime', icon: 'TrendingUp', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'Channel Expansion', message: 'New marketing channel viable.', tone: 'vip_bell', icon: 'Globe', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Engagement Surge', message: 'Content is resonating with audience.', tone: 'success_chime', icon: 'Heart', accentColor: 'from-rose-500 to-pink-500' },
    workflow: { title: 'Content Calendar', message: 'Scheduled content needs attention.', tone: 'low_ping', icon: 'Calendar', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'Trend Alert', message: 'Emerging trend worth exploring.', tone: 'info_bell', icon: 'Lightbulb', accentColor: 'from-yellow-500 to-amber-500' },
  },
  demo_manager: {
    demo_request: {
      title: 'Demo Visibility',
      message: 'A demo link is gaining traffic. Ensure uptime for smooth user experience.',
      tone: 'soft_bell',
      icon: 'Monitor',
      accentColor: 'from-blue-500 to-indigo-500',
    },
    new_task: { title: 'Demo Task', message: 'New demo requires configuration.', tone: 'soft_bell', icon: 'Settings', accentColor: 'from-purple-500 to-violet-500' },
    lead_opportunity: { title: 'Conversion Signal', message: 'Demo engagement indicates interest.', tone: 'success_chime', icon: 'UserCheck', accentColor: 'from-green-500 to-emerald-500' },
    client_feedback: { title: 'Demo Feedback', message: 'User experience feedback received.', tone: 'soft_bell', icon: 'MessageSquare', accentColor: 'from-cyan-500 to-teal-500' },
    transaction: { title: 'Demo Costs', message: 'Hosting cost summary available.', tone: 'info_bell', icon: 'Receipt', accentColor: 'from-amber-500 to-orange-500' },
    campaign_update: { title: 'Demo Promotion', message: 'Demo featured in campaign.', tone: 'success_chime', icon: 'Star', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Security Check', message: 'Demo security status needs review.', tone: 'low_ping', icon: 'Shield', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Demo Support', message: 'Additional hands needed for demo prep.', tone: 'info_bell', icon: 'Users', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Demo Down', message: 'Attention required—demo needs restoration.', tone: 'warning_ping', icon: 'AlertCircle', accentColor: 'from-red-500 to-orange-500' },
    system_insight: { title: 'Uptime Report', message: 'Demo health metrics available.', tone: 'info_bell', icon: 'Activity', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Usage Analytics', message: 'Demo engagement data updated.', tone: 'success_chime', icon: 'BarChart', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'New Demo', message: 'New product demo creation opportunity.', tone: 'vip_bell', icon: 'Plus', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'High Traffic', message: 'Demo experiencing increased visits.', tone: 'success_chime', icon: 'TrendingUp', accentColor: 'from-cyan-500 to-blue-500' },
    workflow: { title: 'Maintenance Window', message: 'Scheduled maintenance approaching.', tone: 'low_ping', icon: 'Clock', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'Feature Update', message: 'Demo enhancement available.', tone: 'info_bell', icon: 'Zap', accentColor: 'from-yellow-500 to-amber-500' },
  },
  influencer: {
    engagement: {
      title: 'Engagement Rising',
      message: 'Your link activity is growing! Keep visibility up to maximize conversion.',
      tone: 'success_chime',
      icon: 'TrendingUp',
      accentColor: 'from-pink-500 to-rose-500',
    },
    new_task: { title: 'Content Brief', message: 'New promotional content ready for you.', tone: 'soft_bell', icon: 'FileText', accentColor: 'from-purple-500 to-violet-500' },
    lead_opportunity: { title: 'Follower Lead', message: 'Your audience is converting.', tone: 'success_chime', icon: 'Users', accentColor: 'from-blue-500 to-indigo-500' },
    demo_request: { title: 'Product Preview', message: 'New demo available to showcase.', tone: 'soft_bell', icon: 'Play', accentColor: 'from-cyan-500 to-teal-500' },
    client_feedback: { title: 'Audience Voice', message: 'Your followers are responding.', tone: 'success_chime', icon: 'MessageCircle', accentColor: 'from-green-500 to-emerald-500' },
    transaction: { title: 'Earnings Alert', message: 'Commission credited to your wallet.', tone: 'success_chime', icon: 'DollarSign', accentColor: 'from-green-500 to-teal-500' },
    campaign_update: { title: 'Campaign Live', message: 'Your promotion is now active.', tone: 'success_chime', icon: 'Megaphone', accentColor: 'from-amber-500 to-orange-500' },
    compliance: { title: 'Content Guidelines', message: 'Quick review of brand guidelines.', tone: 'low_ping', icon: 'BookOpen', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Collaboration', message: 'Partnership opportunity available.', tone: 'vip_bell', icon: 'Handshake', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Urgent Brief', message: 'Time-sensitive content needed.', tone: 'warning_ping', icon: 'Clock', accentColor: 'from-orange-500 to-red-500' },
    system_insight: { title: 'Analytics Update', message: 'Your performance data refreshed.', tone: 'info_bell', icon: 'BarChart2', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Tier Progress', message: 'You are climbing the leaderboard.', tone: 'success_chime', icon: 'Award', accentColor: 'from-yellow-500 to-amber-500' },
    growth_opportunity: { title: 'Tier Upgrade', message: 'You qualify for higher tier benefits.', tone: 'vip_bell', icon: 'Crown', accentColor: 'from-amber-500 to-yellow-500' },
    workflow: { title: 'Deadline Reminder', message: 'Content submission window closing.', tone: 'pending_tick', icon: 'AlarmClock', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'New Feature', message: 'Enhanced link tools available.', tone: 'info_bell', icon: 'Link', accentColor: 'from-indigo-500 to-purple-500' },
  },
  seo: {
    growth_opportunity: {
      title: 'Growth Window',
      message: 'Search signals suggest optimization opportunity. Review keywords to elevate ranking.',
      tone: 'info_bell',
      icon: 'Search',
      accentColor: 'from-blue-500 to-indigo-500',
    },
    new_task: { title: 'SEO Task', message: 'New optimization task assigned.', tone: 'soft_bell', icon: 'FileSearch', accentColor: 'from-purple-500 to-violet-500' },
    lead_opportunity: { title: 'Traffic Source', message: 'New traffic channel identified.', tone: 'success_chime', icon: 'Globe', accentColor: 'from-green-500 to-emerald-500' },
    demo_request: { title: 'Demo SEO', message: 'Demo page needs SEO optimization.', tone: 'soft_bell', icon: 'Code', accentColor: 'from-cyan-500 to-teal-500' },
    client_feedback: { title: 'Content Request', message: 'Content enhancement needed.', tone: 'soft_bell', icon: 'Edit', accentColor: 'from-amber-500 to-orange-500' },
    transaction: { title: 'Tool Subscription', message: 'SEO tool billing update.', tone: 'info_bell', icon: 'CreditCard', accentColor: 'from-green-500 to-teal-500' },
    campaign_update: { title: 'Ranking Update', message: 'Keyword positions have shifted.', tone: 'info_bell', icon: 'TrendingUp', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Content Review', message: 'SEO content needs compliance check.', tone: 'low_ping', icon: 'FileCheck', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Content Writer', message: 'New content support available.', tone: 'info_bell', icon: 'UserPlus', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Algorithm Alert', message: 'Search algorithm update detected.', tone: 'warning_ping', icon: 'AlertTriangle', accentColor: 'from-orange-500 to-red-500' },
    system_insight: { title: 'Analytics Insight', message: 'Search console data reveals patterns.', tone: 'info_bell', icon: 'BarChart', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Traffic Growth', message: 'Organic traffic trending upward.', tone: 'success_chime', icon: 'ArrowUp', accentColor: 'from-green-500 to-teal-500' },
    engagement: { title: 'Page Performance', message: 'Core web vitals improved.', tone: 'success_chime', icon: 'Zap', accentColor: 'from-cyan-500 to-blue-500' },
    workflow: { title: 'Audit Due', message: 'Scheduled SEO audit approaching.', tone: 'low_ping', icon: 'Calendar', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'SEO Update', message: 'New optimization techniques available.', tone: 'info_bell', icon: 'Lightbulb', accentColor: 'from-yellow-500 to-amber-500' },
  },
  task_manager: {
    workflow: {
      title: 'Workflow Update',
      message: 'A new request is queuing. Assign promptly to sustain project flow.',
      tone: 'low_ping',
      icon: 'Layers',
      accentColor: 'from-orange-500 to-amber-500',
    },
    new_task: { title: 'New Task', message: 'Task ready for assignment.', tone: 'soft_bell', icon: 'Plus', accentColor: 'from-blue-500 to-indigo-500' },
    lead_opportunity: { title: 'Resource Match', message: 'Optimal developer available.', tone: 'info_bell', icon: 'UserCheck', accentColor: 'from-green-500 to-emerald-500' },
    demo_request: { title: 'Demo Task', message: 'Demo-related task created.', tone: 'soft_bell', icon: 'Monitor', accentColor: 'from-cyan-500 to-teal-500' },
    client_feedback: { title: 'Client Input', message: 'Task feedback received.', tone: 'soft_bell', icon: 'MessageSquare', accentColor: 'from-purple-500 to-violet-500' },
    transaction: { title: 'Budget Alert', message: 'Task budget needs attention.', tone: 'info_bell', icon: 'DollarSign', accentColor: 'from-green-500 to-teal-500' },
    campaign_update: { title: 'Sprint Update', message: 'Sprint progress report ready.', tone: 'info_bell', icon: 'Flag', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Policy Check', message: 'Task compliance verification needed.', tone: 'low_ping', icon: 'Shield', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Team Capacity', message: 'Developer availability updated.', tone: 'info_bell', icon: 'Users', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Priority Task', message: 'Urgent task needs immediate assignment.', tone: 'warning_ping', icon: 'AlertCircle', accentColor: 'from-red-500 to-rose-500' },
    system_insight: { title: 'Pipeline Insight', message: 'Task metrics reveal bottlenecks.', tone: 'info_bell', icon: 'BarChart', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Team Performance', message: 'Delivery metrics improved.', tone: 'success_chime', icon: 'TrendingUp', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'Process Improvement', message: 'Workflow optimization available.', tone: 'info_bell', icon: 'Settings', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Task Progress', message: 'Milestone checkpoint reached.', tone: 'success_chime', icon: 'CheckCircle', accentColor: 'from-cyan-500 to-blue-500' },
    innovation: { title: 'Tool Update', message: 'Enhanced task management features.', tone: 'info_bell', icon: 'Zap', accentColor: 'from-yellow-500 to-amber-500' },
  },
  client_success: {
    client_feedback: {
      title: 'Care Attention',
      message: 'A feedback item is awaiting your touch. Your guidance protects loyalty.',
      tone: 'soft_bell',
      icon: 'Heart',
      accentColor: 'from-rose-500 to-pink-500',
    },
    new_task: { title: 'Client Action', message: 'Client engagement task ready.', tone: 'soft_bell', icon: 'Target', accentColor: 'from-blue-500 to-indigo-500' },
    lead_opportunity: { title: 'Upsell Signal', message: 'Client shows expansion interest.', tone: 'success_chime', icon: 'TrendingUp', accentColor: 'from-green-500 to-emerald-500' },
    demo_request: { title: 'Demo Request', message: 'Client needs demo assistance.', tone: 'soft_bell', icon: 'Play', accentColor: 'from-cyan-500 to-teal-500' },
    transaction: { title: 'Renewal Alert', message: 'Client renewal approaching.', tone: 'info_bell', icon: 'RefreshCw', accentColor: 'from-amber-500 to-orange-500' },
    campaign_update: { title: 'Success Story', message: 'Client achievement worth celebrating.', tone: 'success_chime', icon: 'Trophy', accentColor: 'from-yellow-500 to-amber-500' },
    compliance: { title: 'SLA Review', message: 'Service level review needed.', tone: 'low_ping', icon: 'FileText', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Account Transfer', message: 'Client handoff coordination needed.', tone: 'info_bell', icon: 'UserSwitch', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'At-Risk Client', message: 'Client satisfaction needs immediate attention.', tone: 'warning_ping', icon: 'AlertTriangle', accentColor: 'from-red-500 to-rose-500' },
    system_insight: { title: 'Health Score', message: 'Client health metrics updated.', tone: 'info_bell', icon: 'Activity', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'NPS Update', message: 'Client satisfaction trending positive.', tone: 'success_chime', icon: 'ThumbsUp', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'Expansion Ready', message: 'Client ready for service upgrade.', tone: 'vip_bell', icon: 'ArrowUp', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Engagement Milestone', message: 'Client reached key milestone.', tone: 'success_chime', icon: 'Award', accentColor: 'from-cyan-500 to-blue-500' },
    workflow: { title: 'Check-in Due', message: 'Scheduled client review approaching.', tone: 'low_ping', icon: 'Calendar', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'Feature Adoption', message: 'New feature available for clients.', tone: 'info_bell', icon: 'Sparkles', accentColor: 'from-purple-500 to-pink-500' },
  },
  performance: {
    performance_insight: {
      title: 'Insight Available',
      message: 'A new behavior pattern is detected. Review for growth and empowerment.',
      tone: 'info_bell',
      icon: 'Activity',
      accentColor: 'from-cyan-500 to-blue-500',
    },
    new_task: { title: 'Review Task', message: 'Performance review ready.', tone: 'soft_bell', icon: 'ClipboardList', accentColor: 'from-blue-500 to-indigo-500' },
    lead_opportunity: { title: 'Top Performer', message: 'Star performer identified.', tone: 'success_chime', icon: 'Star', accentColor: 'from-yellow-500 to-amber-500' },
    demo_request: { title: 'Demo Metrics', message: 'Demo performance data ready.', tone: 'info_bell', icon: 'BarChart2', accentColor: 'from-purple-500 to-violet-500' },
    client_feedback: { title: 'Feedback Analysis', message: 'Performance feedback compiled.', tone: 'soft_bell', icon: 'MessageCircle', accentColor: 'from-green-500 to-emerald-500' },
    transaction: { title: 'Incentive Due', message: 'Performance bonus processing.', tone: 'success_chime', icon: 'Gift', accentColor: 'from-amber-500 to-orange-500' },
    campaign_update: { title: 'KPI Update', message: 'Key metrics have shifted.', tone: 'info_bell', icon: 'TrendingUp', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Policy Adherence', message: 'Compliance metrics ready.', tone: 'low_ping', icon: 'CheckSquare', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Development Plan', message: 'Growth opportunity for team member.', tone: 'info_bell', icon: 'GraduationCap', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Urgent Review', message: 'Performance concern needs attention.', tone: 'warning_ping', icon: 'AlertTriangle', accentColor: 'from-red-500 to-rose-500' },
    system_insight: { title: 'Analytics Ready', message: 'Performance analytics updated.', tone: 'info_bell', icon: 'PieChart', accentColor: 'from-blue-500 to-cyan-500' },
    growth_opportunity: { title: 'Training Available', message: 'Skill development program ready.', tone: 'vip_bell', icon: 'BookOpen', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Team Engagement', message: 'Engagement scores improved.', tone: 'success_chime', icon: 'Users', accentColor: 'from-green-500 to-teal-500' },
    workflow: { title: 'Review Cycle', message: 'Performance review cycle starting.', tone: 'low_ping', icon: 'RefreshCw', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'Metrics Update', message: 'New performance metrics available.', tone: 'info_bell', icon: 'Zap', accentColor: 'from-yellow-500 to-amber-500' },
  },
  rnd: {
    innovation: {
      title: 'Innovation Hint',
      message: 'Market signals indicate feature opportunities. Explore the path forward.',
      tone: 'vip_bell',
      icon: 'Lightbulb',
      accentColor: 'from-yellow-500 to-amber-500',
    },
    new_task: { title: 'Research Task', message: 'New investigation assigned.', tone: 'soft_bell', icon: 'Search', accentColor: 'from-blue-500 to-indigo-500' },
    lead_opportunity: { title: 'Market Signal', message: 'User demand pattern detected.', tone: 'info_bell', icon: 'TrendingUp', accentColor: 'from-green-500 to-emerald-500' },
    demo_request: { title: 'Prototype Demo', message: 'Prototype ready for showcase.', tone: 'vip_bell', icon: 'Box', accentColor: 'from-purple-500 to-violet-500' },
    client_feedback: { title: 'User Research', message: 'User feedback analysis ready.', tone: 'soft_bell', icon: 'MessageCircle', accentColor: 'from-cyan-500 to-teal-500' },
    transaction: { title: 'Budget Update', message: 'R&D budget allocation updated.', tone: 'info_bell', icon: 'Calculator', accentColor: 'from-amber-500 to-orange-500' },
    campaign_update: { title: 'Trend Analysis', message: 'Market trend report available.', tone: 'info_bell', icon: 'Activity', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Patent Review', message: 'IP documentation needs attention.', tone: 'low_ping', icon: 'Shield', accentColor: 'from-slate-500 to-gray-500' },
    talent: { title: 'Expert Available', message: 'Specialist consultation opportunity.', tone: 'vip_bell', icon: 'UserCheck', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Urgent Discovery', message: 'Critical finding needs review.', tone: 'warning_ping', icon: 'AlertCircle', accentColor: 'from-orange-500 to-red-500' },
    system_insight: { title: 'Data Insight', message: 'Research data reveals patterns.', tone: 'info_bell', icon: 'Database', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Progress Update', message: 'Research milestones achieved.', tone: 'success_chime', icon: 'CheckCircle', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'Breakthrough', message: 'Significant advancement identified.', tone: 'golden_vip_bell', icon: 'Sparkles', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Team Progress', message: 'Research collaboration thriving.', tone: 'success_chime', icon: 'Users', accentColor: 'from-cyan-500 to-blue-500' },
    workflow: { title: 'Sprint Review', message: 'Research sprint ending soon.', tone: 'low_ping', icon: 'Calendar', accentColor: 'from-orange-500 to-amber-500' },
  },
  legal: {
    compliance: {
      title: 'Compliance Notice',
      message: 'A document status needs verification. Review calmly to ensure regulation alignment.',
      tone: 'low_ping',
      icon: 'FileCheck',
      accentColor: 'from-slate-500 to-gray-600',
    },
    new_task: { title: 'Legal Review', message: 'Document requires your expertise.', tone: 'soft_bell', icon: 'FileText', accentColor: 'from-blue-500 to-indigo-500' },
    lead_opportunity: { title: 'Contract Opportunity', message: 'New agreement ready for review.', tone: 'info_bell', icon: 'FileSignature', accentColor: 'from-green-500 to-emerald-500' },
    demo_request: { title: 'Demo Terms', message: 'Demo agreement needs attention.', tone: 'soft_bell', icon: 'Scroll', accentColor: 'from-purple-500 to-violet-500' },
    client_feedback: { title: 'Dispute Notice', message: 'Client concern requires resolution.', tone: 'soft_bell', icon: 'Scale', accentColor: 'from-cyan-500 to-teal-500' },
    transaction: { title: 'Contract Value', message: 'Agreement financials need review.', tone: 'info_bell', icon: 'DollarSign', accentColor: 'from-amber-500 to-orange-500' },
    campaign_update: { title: 'Policy Update', message: 'Marketing compliance update.', tone: 'info_bell', icon: 'BookOpen', accentColor: 'from-pink-500 to-rose-500' },
    talent: { title: 'HR Legal', message: 'Employment matter needs review.', tone: 'soft_bell', icon: 'UserCog', accentColor: 'from-violet-500 to-purple-500' },
    priority_request: { title: 'Urgent Legal', message: 'Time-sensitive matter needs attention.', tone: 'warning_ping', icon: 'AlertTriangle', accentColor: 'from-red-500 to-rose-500' },
    system_insight: { title: 'Risk Assessment', message: 'Legal risk analysis available.', tone: 'info_bell', icon: 'Shield', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Resolution Rate', message: 'Case resolution improving.', tone: 'success_chime', icon: 'TrendingUp', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'IP Opportunity', message: 'Intellectual property to protect.', tone: 'vip_bell', icon: 'Award', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Contract Signed', message: 'Agreement successfully executed.', tone: 'success_chime', icon: 'CheckCircle', accentColor: 'from-green-500 to-teal-500' },
    workflow: { title: 'Deadline Alert', message: 'Filing deadline approaching.', tone: 'pending_tick', icon: 'Clock', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'Regulation Update', message: 'New regulatory guidance available.', tone: 'info_bell', icon: 'Gavel', accentColor: 'from-yellow-500 to-amber-500' },
  },
  hr: {
    talent: {
      title: 'Talent Queue',
      message: 'A new candidate awaits screening. Evaluate to uplift team capability.',
      tone: 'soft_bell',
      icon: 'UserPlus',
      accentColor: 'from-violet-500 to-purple-500',
    },
    new_task: { title: 'HR Action', message: 'People matter needs your attention.', tone: 'soft_bell', icon: 'Users', accentColor: 'from-blue-500 to-indigo-500' },
    lead_opportunity: { title: 'Talent Lead', message: 'Promising candidate identified.', tone: 'success_chime', icon: 'Star', accentColor: 'from-green-500 to-emerald-500' },
    demo_request: { title: 'Onboarding', message: 'New hire orientation needed.', tone: 'soft_bell', icon: 'GraduationCap', accentColor: 'from-cyan-500 to-teal-500' },
    client_feedback: { title: 'Team Feedback', message: 'Employee feedback received.', tone: 'soft_bell', icon: 'MessageCircle', accentColor: 'from-purple-500 to-violet-500' },
    transaction: { title: 'Payroll Update', message: 'Compensation adjustment needed.', tone: 'info_bell', icon: 'DollarSign', accentColor: 'from-amber-500 to-orange-500' },
    campaign_update: { title: 'Employer Brand', message: 'Recruitment campaign update.', tone: 'info_bell', icon: 'Megaphone', accentColor: 'from-pink-500 to-rose-500' },
    compliance: { title: 'Policy Review', message: 'HR policy needs compliance check.', tone: 'low_ping', icon: 'ClipboardCheck', accentColor: 'from-slate-500 to-gray-500' },
    priority_request: { title: 'Urgent HR', message: 'Critical people matter needs attention.', tone: 'warning_ping', icon: 'AlertTriangle', accentColor: 'from-red-500 to-rose-500' },
    system_insight: { title: 'HR Analytics', message: 'People metrics updated.', tone: 'info_bell', icon: 'BarChart', accentColor: 'from-blue-500 to-cyan-500' },
    performance_insight: { title: 'Team Performance', message: 'Team effectiveness improving.', tone: 'success_chime', icon: 'TrendingUp', accentColor: 'from-green-500 to-teal-500' },
    growth_opportunity: { title: 'Development', message: 'Training opportunity available.', tone: 'vip_bell', icon: 'BookOpen', accentColor: 'from-indigo-500 to-purple-500' },
    engagement: { title: 'Culture Win', message: 'Team engagement milestone reached.', tone: 'success_chime', icon: 'Heart', accentColor: 'from-rose-500 to-pink-500' },
    workflow: { title: 'Review Cycle', message: 'Performance reviews due soon.', tone: 'low_ping', icon: 'Calendar', accentColor: 'from-orange-500 to-amber-500' },
    innovation: { title: 'HR Tech', message: 'New people tools available.', tone: 'info_bell', icon: 'Settings', accentColor: 'from-yellow-500 to-amber-500' },
  },
};

// Fallback for roles not explicitly defined
export const getTemplateForRole = (
  role: string, 
  category: NotificationCategory
): NotificationTemplate => {
  const roleConfig = roleTemplates[role] || roleTemplates.support;
  return roleConfig[category] || roleConfig.new_task;
};

export default roleTemplates;
