// @ts-nocheck
// Author career progression — 10 unique stages. UI/UX data only.
import type { DeveloperStage } from "./developer-stages";

export const AUTHOR_STAGES: DeveloperStage[] = [
  {
    n: 1, code: "STAGE 01",
    title: "First Draft", theme: "The Blank Page",
    tagline: "One page. One idea. The story begins.",
    material: "Parchment", trophyShape: "cup", medalShape: "circle",
    passportMotif: "Rough Paper", badgeStyle: "Wax Dot",
    nameplate: "Etched Parchment", ribbon: ["#c9a37a", "#5a3a20"],
    unlock: "starter",
    bg: {
      gradient: "radial-gradient(1200px 500px at 20% 0%, rgba(201,163,122,0.22), transparent 60%), linear-gradient(160deg, #1a140a 0%, #0c0805 100%)",
      accent: "#c9a37a", glow: "rgba(201,163,122,0.5)", particle: "#e6c9a1",
    },
    rewards: [
      { label: "Author Draft Passport", kind: "passport" },
      { label: "Rookie Writer ID", kind: "identity" },
      { label: "Parchment Cup", kind: "trophy" },
      { label: "First Page Medal", kind: "medal" },
      { label: "Starter Quill Badge", kind: "badge" },
      { label: "Draft Certificate", kind: "certificate" },
    ],
    animation: ["Ink Splash", "Page Turn", "Soft Glow"],
    sound: ["Quill Scratch", "Page Turn", "UI Unlock"],
  },
  {
    n: 2, code: "STAGE 02",
    title: "Contributor", theme: "First Byline",
    tagline: "You have a byline. Readers know your name.",
    material: "Bronze Ink", trophyShape: "flame", medalShape: "hexagon",
    passportMotif: "Ink-Splattered Bronze", badgeStyle: "Enamel Quill",
    nameplate: "Brushed Bronze", ribbon: ["#cd7f32", "#5c3410"],
    unlock: "bronze",
    bg: {
      gradient: "radial-gradient(1200px 500px at 80% 0%, rgba(205,127,50,0.26), transparent 60%), linear-gradient(160deg, #1c150c 0%, #100a06 100%)",
      accent: "#cd7f32", glow: "rgba(205,127,50,0.55)", particle: "#f2c98a",
    },
    rewards: [
      { label: "Byline Passport", kind: "passport" },
      { label: "Bronze Quill Trophy", kind: "trophy" },
      { label: "First Byline Medal", kind: "medal" },
      { label: "Contributor Badge", kind: "badge" },
      { label: "Byline Certificate", kind: "certificate" },
      { label: "Bronze Frame", kind: "frame" },
    ],
    animation: ["Ink Bloom", "Passport Flip", "Byline Reveal"],
    sound: ["Typewriter", "Bell Chime", "Digital Unlock"],
  },
  {
    n: 3, code: "STAGE 03",
    title: "Published Author", theme: "Silver Spine",
    tagline: "A finished book on the shelf. The first of many.",
    material: "Silver Foil", trophyShape: "obelisk", medalShape: "shield",
    passportMotif: "Silver Foil Weave", badgeStyle: "Polished Silver",
    nameplate: "Silver Chrome", ribbon: ["#d9d9d9", "#5a6472"],
    unlock: "silver",
    bg: {
      gradient: "radial-gradient(1200px 500px at 50% 0%, rgba(200,210,225,0.22), transparent 60%), linear-gradient(160deg, #10151d 0%, #070a0f 100%)",
      accent: "#c8d2e1", glow: "rgba(200,210,225,0.5)", particle: "#eaf2ff",
    },
    rewards: [
      { label: "Silver Passport", kind: "passport" },
      { label: "Silver Spine Trophy", kind: "trophy" },
      { label: "Published Medal", kind: "medal" },
      { label: "Author Badge", kind: "badge" },
      { label: "Silver Certificate", kind: "certificate" },
      { label: "Silver Identity Card", kind: "identity" },
    ],
    animation: ["Hologram Reveal", "Rotating Book", "Silver Sheen"],
    sound: ["Metal Impact", "Crystal Ring", "Premium Notification"],
  },
  {
    n: 4, code: "STAGE 04",
    title: "Bestseller", theme: "Gold Leaf",
    tagline: "The list is on the door. Your book is in the window.",
    material: "Gold Leaf", trophyShape: "diamond", medalShape: "star",
    passportMotif: "Gold Leaf Manuscript", badgeStyle: "Gold Plated",
    nameplate: "Engraved Gold Bar", ribbon: ["#f5c542", "#7a5008"],
    unlock: "gold",
    bg: {
      gradient: "radial-gradient(1200px 500px at 30% 0%, rgba(245,197,66,0.28), transparent 60%), linear-gradient(160deg, #1a1508 0%, #0a0803 100%)",
      accent: "#f5c542", glow: "rgba(245,197,66,0.6)", particle: "#ffe28a",
    },
    rewards: [
      { label: "Gold Passport", kind: "passport" },
      { label: "Bestseller Trophy", kind: "trophy" },
      { label: "Gold Medal", kind: "medal" },
      { label: "Bestseller Badge", kind: "badge" },
      { label: "Premium Certificate", kind: "certificate" },
      { label: "Gold Frame", kind: "frame" },
    ],
    animation: ["Golden Rays", "Luxury Shine", "Spotlight"],
    sound: ["Golden Bell", "Achievement Fanfare", "Energy Pulse"],
  },
  {
    n: 5, code: "STAGE 05",
    title: "Featured Author", theme: "Platinum Feature",
    tagline: "On the front page. Curated by editors.",
    material: "Platinum", trophyShape: "orb", medalShape: "octagon",
    passportMotif: "Platinum Filigree", badgeStyle: "Platinum Enamel",
    nameplate: "Polished Platinum", ribbon: ["#e5e4e2", "#7d8794"],
    unlock: "elite",
    bg: {
      gradient: "radial-gradient(1200px 500px at 60% 0%, rgba(229,228,226,0.22), transparent 60%), linear-gradient(160deg, #14171c 0%, #08090c 100%)",
      accent: "#e5e4e2", glow: "rgba(229,228,226,0.5)", particle: "#f7f8fb",
    },
    rewards: [
      { label: "Featured Passport", kind: "passport" },
      { label: "Editor's Pick Trophy", kind: "trophy" },
      { label: "Feature Medal", kind: "medal" },
      { label: "Featured Badge", kind: "badge" },
      { label: "Platinum Frame", kind: "frame" },
    ],
    animation: ["Cinematic Zoom", "Aurora Sweep", "Ambient Lighting"],
    sound: ["Orchestral Hit", "Digital Chime", "Premium Alert"],
  },
  {
    n: 6, code: "STAGE 06",
    title: "Series Master", theme: "Crystal Volume",
    tagline: "A series that readers wait for.",
    material: "Crystal Glass", trophyShape: "prism", medalShape: "diamond",
    passportMotif: "Etched Crystal Manuscript", badgeStyle: "Beveled Glass",
    nameplate: "Frosted Crystal Slab", ribbon: ["#a78bfa", "#4b2ea5"],
    unlock: "diamond",
    bg: {
      gradient: "radial-gradient(1200px 500px at 40% 0%, rgba(167,139,250,0.28), transparent 60%), linear-gradient(160deg, #100823 0%, #06030e 100%)",
      accent: "#a78bfa", glow: "rgba(167,139,250,0.55)", particle: "#e0d5ff",
    },
    rewards: [
      { label: "Series Passport", kind: "passport" },
      { label: "Volume Trophy", kind: "trophy" },
      { label: "Crystal Medal", kind: "medal" },
      { label: "Series Badge", kind: "badge" },
      { label: "Executive Certificate", kind: "certificate" },
    ],
    animation: ["Prism Refraction", "Slow Rotation", "Holographic Sheen"],
    sound: ["Crystal Ring", "Glass Chime", "Ambient Pad"],
  },
  {
    n: 7, code: "STAGE 07",
    title: "Reader's Favorite", theme: "Titanium Ribbon",
    tagline: "Voted. Reviewed. Remembered.",
    material: "Titanium", trophyShape: "wing", medalShape: "gear",
    passportMotif: "Titanium Foil", badgeStyle: "Diamond Cut",
    nameplate: "Laser-Etched Titanium", ribbon: ["#b5c0d0", "#3a4a5e"],
    unlock: "legend",
    bg: {
      gradient: "radial-gradient(1200px 500px at 70% 0%, rgba(181,192,208,0.22), transparent 60%), linear-gradient(160deg, #0e1319 0%, #05080b 100%)",
      accent: "#b5c0d0", glow: "rgba(120,255,240,0.4)", particle: "#7de1d3",
    },
    rewards: [
      { label: "Titanium Trophy", kind: "trophy" },
      { label: "Reader's Choice Medal", kind: "medal" },
      { label: "Elite Passport", kind: "passport" },
      { label: "Reader Favorite Badge", kind: "badge" },
      { label: "Luxury Nameplate", kind: "nameplate" },
    ],
    animation: ["Electric Arc", "Diamond Sparkle", "Titanium Shine"],
    sound: ["Electric Spark", "Diamond Ring", "Cinematic Rise"],
  },
  {
    n: 8, code: "STAGE 08",
    title: "Master Author", theme: "Obsidian Manuscript",
    tagline: "You define the genre. Peers cite your work.",
    material: "Obsidian & Amethyst", trophyShape: "tower", medalShape: "sun",
    passportMotif: "Obsidian Sigil", badgeStyle: "Amethyst Inlay",
    nameplate: "Obsidian Slab", ribbon: ["#c084fc", "#3b0f5c"],
    unlock: "master",
    bg: {
      gradient: "radial-gradient(1200px 500px at 40% 0%, rgba(192,132,252,0.32), transparent 60%), linear-gradient(160deg, #0f0819 0%, #050310 100%)",
      accent: "#c084fc", glow: "rgba(192,132,252,0.6)", particle: "#e4c9ff",
    },
    rewards: [
      { label: "Master Trophy", kind: "collection" },
      { label: "Master Passport", kind: "passport" },
      { label: "Master Badge", kind: "badge" },
      { label: "Master Medal", kind: "medal" },
      { label: "Executive Identity", kind: "identity" },
    ],
    animation: ["Amethyst Bloom", "Sigil Reveal", "Museum Spotlight"],
    sound: ["Deep Bell", "Orchestral Swell", "Ceremonial Gong"],
  },
  {
    n: 9, code: "STAGE 09",
    title: "Legendary Author", theme: "Solar Manuscript",
    tagline: "Curriculum-listed. Studied. Preserved.",
    material: "24k Legend Gold", trophyShape: "star", medalShape: "laurel",
    passportMotif: "Solar Emboss", badgeStyle: "Legend Seal",
    nameplate: "24k Legend Plaque", ribbon: ["#facc15", "#7a3e00"],
    unlock: "legend",
    bg: {
      gradient: "radial-gradient(1400px 600px at 50% 0%, rgba(250,204,21,0.35), transparent 60%), linear-gradient(160deg, #1a1305 0%, #0a0702 100%)",
      accent: "#facc15", glow: "rgba(250,204,21,0.7)", particle: "#fff2a8",
    },
    rewards: [
      { label: "Legend Trophy", kind: "trophy" },
      { label: "Legend Medal", kind: "medal" },
      { label: "Legend Passport", kind: "passport" },
      { label: "Legend Badge", kind: "badge" },
      { label: "Legend Certificate", kind: "certificate" },
    ],
    animation: ["Sunburst Halo", "Legend Rays", "Sparkle Rain"],
    sound: ["Victory Orchestra", "Golden Bell", "Legend Fanfare"],
  },
  {
    n: 10, code: "STAGE 10",
    title: "Founding Author", theme: "Founder Library",
    tagline: "Your bookshelf became the library.",
    material: "Meteorite · Diamond · Founder Gold", trophyShape: "crown", medalShape: "phoenix",
    passportMotif: "Founder Sigil, Meteorite Cover", badgeStyle: "Founder Crown Seal",
    nameplate: "Meteorite & Diamond Plaque", ribbon: ["#fff2b0", "#8a5a00"],
    unlock: "founder",
    bg: {
      gradient: "radial-gradient(1600px 700px at 50% 0%, rgba(255,242,176,0.35), transparent 65%), radial-gradient(900px 500px at 50% 100%, rgba(200,120,255,0.25), transparent 60%), linear-gradient(160deg, #1a1204 0%, #05030a 100%)",
      accent: "#fff2b0", glow: "rgba(255,242,176,0.75)", particle: "#ffe98a",
    },
    rewards: [
      { label: "Founder Trophy", kind: "trophy" },
      { label: "Founder Crown", kind: "crown" },
      { label: "Founder Medal", kind: "medal" },
      { label: "Founder Passport", kind: "passport" },
      { label: "Founder Badge", kind: "badge" },
      { label: "Founder Certificate", kind: "certificate" },
      { label: "Founder Library", kind: "museum" },
    ],
    animation: ["Library Cinematic", "Crown Descent", "Aurora Fanfare", "Phoenix Rise"],
    sound: ["Founder Fanfare", "Choir Swell", "Ceremonial Gong"],
  },
];
