// @ts-nocheck
// Vendor career progression — 10 unique stages. UI/UX data only.
import type { DeveloperStage } from "./developer-stages";

export const VENDOR_STAGES: DeveloperStage[] = [
  {
    n: 1, code: "STAGE 01",
    title: "New Storefront", theme: "First Listing",
    tagline: "Shutter opens. The first item goes live.",
    material: "Copper", trophyShape: "cup", medalShape: "circle",
    passportMotif: "Market Grid", badgeStyle: "Copper Pin",
    nameplate: "Etched Copper Plate", ribbon: ["#b87333", "#6b3a1f"],
    unlock: "starter",
    bg: {
      gradient: "radial-gradient(1200px 500px at 20% 0%, rgba(184,115,51,0.22), transparent 60%), linear-gradient(160deg, #14120a 0%, #0a0805 100%)",
      accent: "#b87333", glow: "rgba(184,115,51,0.55)", particle: "#e8b47a",
    },
    rewards: [
      { label: "Vendor Passport", kind: "passport" },
      { label: "Storefront ID", kind: "identity" },
      { label: "Copper Storefront Trophy", kind: "trophy" },
      { label: "First Listing Medal", kind: "medal" },
      { label: "Starter Vendor Badge", kind: "badge" },
      { label: "Storefront Certificate", kind: "certificate" },
    ],
    animation: ["Shutter Rise", "Signboard Glow", "Small Confetti"],
    sound: ["Cash Ping", "Bell Chime", "UI Unlock"],
  },
  {
    n: 2, code: "STAGE 02",
    title: "Verified Vendor", theme: "First Reviews",
    tagline: "Ratings arrive. Reputation begins.",
    material: "Bronze", trophyShape: "flame", medalShape: "hexagon",
    passportMotif: "Bronze Storefront Emboss", badgeStyle: "Enamel Storefront",
    nameplate: "Brushed Bronze", ribbon: ["#cd7f32", "#5c3410"],
    unlock: "bronze",
    bg: {
      gradient: "radial-gradient(1200px 500px at 80% 0%, rgba(205,127,50,0.26), transparent 60%), linear-gradient(160deg, #1c150c 0%, #100a06 100%)",
      accent: "#cd7f32", glow: "rgba(205,127,50,0.55)", particle: "#f2c98a",
    },
    rewards: [
      { label: "Bronze Passport", kind: "passport" },
      { label: "Bronze Storefront Trophy", kind: "trophy" },
      { label: "Verified Medal", kind: "medal" },
      { label: "Verified Vendor Badge", kind: "badge" },
      { label: "Bronze Certificate", kind: "certificate" },
    ],
    animation: ["Review Stars Rise", "Signboard Shine", "Card Shine"],
    sound: ["Register Ding", "UI Sweep", "Digital Unlock"],
  },
  {
    n: 3, code: "STAGE 03",
    title: "Trusted Vendor", theme: "Silver Shelf",
    tagline: "Repeat customers. Steady ratings.",
    material: "Silver", trophyShape: "obelisk", medalShape: "shield",
    passportMotif: "Silver Shelving", badgeStyle: "Polished Silver",
    nameplate: "Silver Chrome", ribbon: ["#d9d9d9", "#5a6472"],
    unlock: "silver",
    bg: {
      gradient: "radial-gradient(1200px 500px at 50% 0%, rgba(200,210,225,0.22), transparent 60%), linear-gradient(160deg, #10151d 0%, #070a0f 100%)",
      accent: "#c8d2e1", glow: "rgba(200,210,225,0.5)", particle: "#eaf2ff",
    },
    rewards: [
      { label: "Silver Passport", kind: "passport" },
      { label: "Silver Shelf Trophy", kind: "trophy" },
      { label: "Trust Medal", kind: "medal" },
      { label: "Trusted Vendor Badge", kind: "badge" },
      { label: "Silver Certificate", kind: "certificate" },
      { label: "Silver Identity Card", kind: "identity" },
    ],
    animation: ["Hologram Reveal", "Rotating Storefront", "Silver Sheen"],
    sound: ["Metal Impact", "Crystal Ring", "Premium Notification"],
  },
  {
    n: 4, code: "STAGE 04",
    title: "Five-Star Vendor", theme: "Gold Storefront",
    tagline: "Five-star streak. Customers write love letters.",
    material: "Gold", trophyShape: "diamond", medalShape: "star",
    passportMotif: "Gold Storefront Leaf", badgeStyle: "Gold Plated",
    nameplate: "Engraved Gold Bar", ribbon: ["#f5c542", "#7a5008"],
    unlock: "gold",
    bg: {
      gradient: "radial-gradient(1200px 500px at 30% 0%, rgba(52,211,153,0.28), transparent 60%), linear-gradient(160deg, #0a1a12 0%, #030a06 100%)",
      accent: "#34d399", glow: "rgba(52,211,153,0.6)", particle: "#a7f3d0",
    },
    rewards: [
      { label: "Gold Passport", kind: "passport" },
      { label: "Five-Star Trophy", kind: "trophy" },
      { label: "Gold Medal", kind: "medal" },
      { label: "Five-Star Badge", kind: "badge" },
      { label: "Premium Certificate", kind: "certificate" },
      { label: "Gold Frame", kind: "frame" },
    ],
    animation: ["Golden Rays", "Emerald Shine", "Spotlight"],
    sound: ["Golden Bell", "Achievement Fanfare", "Energy Pulse"],
  },
  {
    n: 5, code: "STAGE 05",
    title: "Preferred Vendor", theme: "Platinum Aisle",
    tagline: "Curated aisle. Priority placement.",
    material: "Platinum", trophyShape: "orb", medalShape: "octagon",
    passportMotif: "Platinum Aisle", badgeStyle: "Platinum Enamel",
    nameplate: "Polished Platinum", ribbon: ["#e5e4e2", "#7d8794"],
    unlock: "elite",
    bg: {
      gradient: "radial-gradient(1200px 500px at 60% 0%, rgba(229,228,226,0.22), transparent 60%), linear-gradient(160deg, #14171c 0%, #08090c 100%)",
      accent: "#e5e4e2", glow: "rgba(229,228,226,0.5)", particle: "#f7f8fb",
    },
    rewards: [
      { label: "Preferred Passport", kind: "passport" },
      { label: "Preferred Vendor Trophy", kind: "trophy" },
      { label: "Preferred Medal", kind: "medal" },
      { label: "Preferred Badge", kind: "badge" },
      { label: "Platinum Frame", kind: "frame" },
    ],
    animation: ["Cinematic Zoom", "Aurora Sweep", "Ambient Lighting"],
    sound: ["Orchestral Hit", "Digital Chime", "Premium Alert"],
  },
  {
    n: 6, code: "STAGE 06",
    title: "Marketplace Elite", theme: "Crystal Display",
    tagline: "Featured across the marketplace.",
    material: "Crystal Glass", trophyShape: "prism", medalShape: "diamond",
    passportMotif: "Etched Crystal", badgeStyle: "Beveled Glass",
    nameplate: "Frosted Crystal Slab", ribbon: ["#8de9ff", "#0b6ea6"],
    unlock: "diamond",
    bg: {
      gradient: "radial-gradient(1200px 500px at 40% 0%, rgba(141,233,255,0.28), transparent 60%), linear-gradient(160deg, #071824 0%, #030a11 100%)",
      accent: "#8de9ff", glow: "rgba(141,233,255,0.55)", particle: "#c7f3ff",
    },
    rewards: [
      { label: "Elite Passport", kind: "passport" },
      { label: "Glass Storefront Trophy", kind: "trophy" },
      { label: "Crystal Medal", kind: "medal" },
      { label: "Marketplace Elite Badge", kind: "badge" },
      { label: "Executive Certificate", kind: "certificate" },
    ],
    animation: ["Prism Refraction", "Slow Rotation", "Holographic Sheen"],
    sound: ["Crystal Ring", "Glass Chime", "Ambient Pad"],
  },
  {
    n: 7, code: "STAGE 07",
    title: "Category Champion", theme: "Titanium Category",
    tagline: "You define the category. Others compare to you.",
    material: "Titanium", trophyShape: "wing", medalShape: "gear",
    passportMotif: "Titanium Machined", badgeStyle: "Diamond Cut",
    nameplate: "Laser-Etched Titanium", ribbon: ["#b5c0d0", "#3a4a5e"],
    unlock: "legend",
    bg: {
      gradient: "radial-gradient(1200px 500px at 70% 0%, rgba(181,192,208,0.22), transparent 60%), linear-gradient(160deg, #0e1319 0%, #05080b 100%)",
      accent: "#b5c0d0", glow: "rgba(120,255,240,0.4)", particle: "#7de1d3",
    },
    rewards: [
      { label: "Titanium Trophy", kind: "trophy" },
      { label: "Category Champion Medal", kind: "medal" },
      { label: "Elite Passport", kind: "passport" },
      { label: "Category Badge", kind: "badge" },
      { label: "Luxury Nameplate", kind: "nameplate" },
    ],
    animation: ["Electric Arc", "Diamond Sparkle", "Titanium Shine"],
    sound: ["Electric Spark", "Diamond Ring", "Cinematic Rise"],
  },
  {
    n: 8, code: "STAGE 08",
    title: "Master Vendor", theme: "Obsidian Emporium",
    tagline: "An emporium of trust. Cross-category dominance.",
    material: "Obsidian & Amethyst", trophyShape: "tower", medalShape: "sun",
    passportMotif: "Obsidian Sigil", badgeStyle: "Amethyst Inlay",
    nameplate: "Obsidian Slab", ribbon: ["#c084fc", "#3b0f5c"],
    unlock: "master",
    bg: {
      gradient: "radial-gradient(1200px 500px at 40% 0%, rgba(192,132,252,0.32), transparent 60%), linear-gradient(160deg, #0f0819 0%, #050310 100%)",
      accent: "#c084fc", glow: "rgba(192,132,252,0.6)", particle: "#e4c9ff",
    },
    rewards: [
      { label: "Master Trophy", kind: "collection" },
      { label: "Master Passport", kind: "passport" },
      { label: "Master Badge", kind: "badge" },
      { label: "Master Medal", kind: "medal" },
      { label: "Executive Identity", kind: "identity" },
    ],
    animation: ["Amethyst Bloom", "Sigil Reveal", "Museum Spotlight"],
    sound: ["Deep Bell", "Orchestral Swell", "Ceremonial Gong"],
  },
  {
    n: 9, code: "STAGE 09",
    title: "Legendary Vendor", theme: "Solar Bazaar",
    tagline: "A brand marketplace. Studied by peers.",
    material: "24k Legend Gold", trophyShape: "star", medalShape: "laurel",
    passportMotif: "Solar Emboss", badgeStyle: "Legend Seal",
    nameplate: "24k Legend Plaque", ribbon: ["#facc15", "#7a3e00"],
    unlock: "legend",
    bg: {
      gradient: "radial-gradient(1400px 600px at 50% 0%, rgba(250,204,21,0.35), transparent 60%), linear-gradient(160deg, #1a1305 0%, #0a0702 100%)",
      accent: "#facc15", glow: "rgba(250,204,21,0.7)", particle: "#fff2a8",
    },
    rewards: [
      { label: "Legend Trophy", kind: "trophy" },
      { label: "Legend Medal", kind: "medal" },
      { label: "Legend Passport", kind: "passport" },
      { label: "Legend Badge", kind: "badge" },
      { label: "Legend Certificate", kind: "certificate" },
    ],
    animation: ["Sunburst Halo", "Legend Rays", "Sparkle Rain"],
    sound: ["Victory Orchestra", "Golden Bell", "Legend Fanfare"],
  },
  {
    n: 10, code: "STAGE 10",
    title: "Founding Vendor", theme: "Founder Marketplace",
    tagline: "The marketplace is named after you.",
    material: "Meteorite · Diamond · Founder Gold", trophyShape: "crown", medalShape: "phoenix",
    passportMotif: "Founder Sigil, Meteorite Cover", badgeStyle: "Founder Crown Seal",
    nameplate: "Meteorite & Diamond Plaque", ribbon: ["#fff2b0", "#8a5a00"],
    unlock: "founder",
    bg: {
      gradient: "radial-gradient(1600px 700px at 50% 0%, rgba(255,242,176,0.35), transparent 65%), radial-gradient(900px 500px at 50% 100%, rgba(52,211,153,0.25), transparent 60%), linear-gradient(160deg, #1a1204 0%, #05030a 100%)",
      accent: "#fff2b0", glow: "rgba(255,242,176,0.75)", particle: "#ffe98a",
    },
    rewards: [
      { label: "Founder Trophy", kind: "trophy" },
      { label: "Founder Crown", kind: "crown" },
      { label: "Founder Medal", kind: "medal" },
      { label: "Founder Passport", kind: "passport" },
      { label: "Founder Badge", kind: "badge" },
      { label: "Founder Certificate", kind: "certificate" },
      { label: "Founder Marketplace", kind: "museum" },
    ],
    animation: ["Marketplace Cinematic", "Crown Descent", "Aurora Fanfare"],
    sound: ["Founder Fanfare", "Choir Swell", "Ceremonial Gong"],
  },
];
